# Generated by Django 2.1 on 2019-10-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191021_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='blog.Comment'),
        ),
    ]
