# Generated by Django 2.1 on 2019-10-23 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='blog.Comment'),
        ),
    ]
