# Generated by Django 2.1 on 2019-10-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191023_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
